[{{ cookiecutter.pkgname }}]
source = "jq"
url = "https://www.gogdb.org/data/products/{{ cookiecutter.gog_product_id }}/product.json"
filter = ".dl_installer | map(select(.os == \"linux\"))[0] | .version"
